// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SOAProjekat1GraphQL.Repository;

#nullable disable

namespace SOAProjekat1GraphQL.Migrations
{
    [DbContext(typeof(LogDbContext))]
    partial class LogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SOAProjekat1GraphQL.Repository.LogVal", b =>
                {
                    b.Property<int>("FrameNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FrameLen")
                        .HasColumnType("int");

                    b.Property<double>("FrameTime")
                        .HasColumnType("double");

                    b.Property<int>("IpDst")
                        .HasColumnType("int");

                    b.Property<int>("IpLen")
                        .HasColumnType("int");

                    b.Property<int>("IpSrc")
                        .HasColumnType("int");

                    b.Property<int>("Normality")
                        .HasColumnType("int");

                    b.Property<int>("TcpLen")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("FrameNumber");

                    b.ToTable("LogVals");
                });
#pragma warning restore 612, 618
        }
    }
}
